(require regexp)

(defun main (args)
  (println (regexp:match "hello" "hello"))
  (println (regexp:match "h.llo" "hello"))
  (println (regexp:match "^ab*c$" "ac"))
  (println (regexp:match "ab*c" "abbbc"))
  (println (regexp:match "ab?c" "ac"))
  (println (regexp:match "ab?c" "abc"))
  (println (regexp:match "ab?c" "abbc"))
  (println (regexp:match "^s....$" "steve"))
  (println (regexp:match "^s[ie]x$" "six"))
  (println (regexp:match "^[0123456789]+$" "1234"))
  (println (regexp:match "^[0123456789]+$" "1234.77"))
  )
