(defun main ()
  ;; real square root
  (println (sqrt 1))
  (println (sqrt 2))
  (println (sqrt 3))
  (println (sqrt 4))
  (println (sqrt 5))
  (println (sqrt 6))
  (println (sqrt 7))
  (println (sqrt 8))
  (println (sqrt 9))
  (println (sqrt 10))

  ;; integer square root
  (println (isqrt 15))
  (println (isqrt 16))
  (println (isqrt 17))
  (println (isqrt 18))
  (println (isqrt 19))
  (println (isqrt 20))
  (println (isqrt 21))
  (println (isqrt 22))
  (println (isqrt 23))
  (println (isqrt 24))
  (println (isqrt 25))
)
