#!/bin/sh

# ensure we're always up to data
rm inception ../slisp || true

# by forcing a rebuild
make inception

# build up the code
cat ../stdlib.slisp lisp-reader.lisp tree.lisp inception.lisp >new.txt

# run
./inception new.txt --repl

# cleanup
rm -f new.txt
